export default [ // this is only a list for the tags available in the create post page
    'node',
    'javascript',
    'c',
    'c++',
    'c#',
    'react',
    'angular',
    'vue',
    'express',
    'axios',
    'redux',
    'recoil',
    'sequelize',
    'mongoose',
    'sql',
    'mongodb',
    'python',
    'flask',
    'puppeteer',
    'jest',
    'java',
    'react native',
    'security',
    'algorithm',
    'web scoket',
    'linux',
    'docker'
];